# Generated by Django 5.0.4 on 2024-05-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(blank=True, choices=[('USA', 'Estados Unidos'), ('BR', 'Brasil'), ('CN', 'China'), ('ING', 'Inglaterra')], max_length=100, null=True),
        ),
    ]
