# Generated by Django 5.0.4 on 2024-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_alter_actor_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='nationality',
            field=models.CharField(choices=[('USA', 'Estados Unidos'), ('BR', 'Brasil'), ('CN', 'China'), ('ING', 'Inglaterra')], max_length=100),
        ),
    ]
