# Generated by Django 5.0.4 on 2024-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_alter_actor_nationality'),
        ('movies', '0002_alter_movie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='movies', to='actors.actor'),
        ),
    ]
